### ISSUE TITLE
Python3 support

### ISSUE THREAD

**Issue by bdferris** [google/transitfeed#239]
_From [celil...@gmail.com](https://code.google.com/u/100078355536618338555/) on June 14, 2010 02:59:59_

Are there any plans to migrate transitfeed to python3? What steps will reproduce the problem? try to run
$ python3 setup.py install What is the expected output? What do you see instead? The program should install. What version of the product are you using? On what operating system? transitfeed-1.2.5 Ubuntu Linux

_Original issue: http://code.google.com/p/googletransitdatafeed/issues/detail?id=239_

**Comment by jacobvalenta** [comment]
Python 3.0 was released 7 years ago.

**Comment by jamescr** [comment]
There is a newer issue (#412) related with python 3 support.

**Comment by jarondl** [comment]
closing in favor of #412
