### ISSUE TITLE
Fix the retrieval of lat and lng while updating stops marker position using location_editor.

### ISSUE THREAD

**Issue by francisboys** [google/transitfeed#384]
Update the fetching of marker position as per google maps javascript v3 (https://developers.google.com/maps/documentation/javascript/reference#Marker) 

I have made the fix here. (Tested locally and works fine now)
https://github.com/francisboys/transitfeed/commit/573e7a49e75c8a1a62b73eae4693a51413b35399

Upgrade from google maps javascript v2 to v3 was done here: https://github.com/google/transitfeed/commit/a720595b7e421651a6c67799d68fb62886e17dde

**Comment by bdferris** [comment]
Fixed in 9a504f97c1b5afc95d2baaad2ed88973114af2bc
