### ISSUE TITLE
overnight schedule marks as timetravel

### ISSUE THREAD

**Issue by yipcma** [google/transitfeed#399]
i experience the issue where the some trip running over midnight is considered timetravel by the validator. thoughts?

**Comment by bileto-roman** [comment]
Are you sure, that your overnight trips are in correct time format ? This caused manny troubles for our young collegue, whose starting with GTFS format.

GTFS specs say: 
"Trips that span multiple dates will have stop times greater than 24:00:00. For example, if a trip begins at 10:30:00 p.m. and ends at 2:15:00 a.m. on the following day, the stop times would be 22:30:00 and 26:15:00. Entering those stop times as 22:30:00 and 02:15:00 would not produce the desired results."

**Comment by yipcma** [comment]
@bileto-roman this is very helpful. Thanks for the hint.
