### ISSUE TITLE
Schedule Viewer fails to show stops (those with yellow markers and times)

### ISSUE THREAD

**Issue by MiskoProgramista** [google/transitfeed#417]
Hello

I noticed recenlty that schedule viewer does not show stops (as a yellow marker + time with it) either when displaying a route shape (displays only shape instead of shape and yellow stop markers and time with it), or when searching for a stop_id (shows nothing at all). (Pic. 1)

Query returns no errors in command prompt window. (Pic. 2)

I've tried to check on different browsers, different machines and with different GTFS files.

![image](https://cloud.githubusercontent.com/assets/13540763/15274242/d5f80a18-1aad-11e6-818a-cc05ff77e5a0.png)
Pic. 1

![image](https://cloud.githubusercontent.com/assets/13540763/15274248/eaa4c208-1aad-11e6-9784-83e5ae506bd5.png)
Pic. 2

**Comment by saltmanCST** [comment]
I've been experiencing the same issue.  This started less than one week ago for me.

**Comment by joordan** [comment]
I am experiencing this issue as well.

**Comment by dimrizo** [comment]
Same problem with me. What could possibly go wrong? Browser blocking any HTML/CSS elements?

**Comment by dimrizo** [comment]
Check out my screenshot. http://prntscr.com/b7tqjx

It says "MarkerWIthLabelNotDefined".

**Comment by dimrizo** [comment]
Okay, I got a quick fix for you guys. It is not the solution, but a quick fix if you have work to do.

go to index.js file in schedule_viewer_files folder, and search for the missing marker.

Ctrl + F and write "MarkerWithLabel". There should only one match in your search. delete it and write "google.map..Marker" before the parenthesis. 

Reload the page and you should have simple markers without the labels though, just to proceed with your work for now.

We wait for a solution.

**Comment by saltmanCST** [comment]
That quick-fix didn't seem to work for me.  I really need the labels anyway, I need to see times on trips.  

I wonder if these tools are dependent on an older version of the Google Maps API that's no longer supported.  I think they recently cut support for version 2.

**Comment by MiskoProgramista** [comment]
It shows the markers but you have to replace "MarkerWithLabel" with "google.maps.Marker", not "google.map..Marker".

**Comment by mani-rai** [comment]
The problem is google maps utility library has moved to github and this hosted library is closed.

SOLUTION:
1. Copy markerwithlabel.js content from here: [https://github.com/printercu/google-maps-utility-library-v3-read-only/blob/master/markerwithlabel/src/markerwithlabel.js](url)
2. Create new javascript file naming it markerwithlabel.js in <transitfeed-app-root>/gtfsscheduleviewer/files directory.
3. Open index.html file from <transitfeed-app-root>/gtfsscheduleviewer/files directory.
4. Replace script src "https://google-maps-utility-library-v3.googlecode.com/svn/tags/markerwithlabel/1.1.9/src/markerwithlabel.js" with "/file/markerwithlabel.js".

**Comment by dimrizo** [comment]
mani-rai's suggestion worked perfectly for me. Thank you.

**Comment by joordan** [comment]
The link for 1 doesn't exist anymore?

**Comment by BraveJhawk** [comment]
joordan: there is something wrong with the hyperlink for it, but manually copying and pasting it worked for me.

**Comment by barbeau** [comment]
I believe there is a PR to fix this at https://github.com/google/transitfeed/pull/425.
