### ISSUE TITLE
Validation tool don't recognize agency_email field in agency.txt

### ISSUE THREAD

**Issue by aledelgo** [google/transitfeed#418]
Using the validation tool I get this warning:

> Unrecognized column agency_email in file agency.txt. This might be a misspelled column name (capitalization matters!). Or it could be extra information (such as a proposed feed extension) that the validator doesn't know about yet. Extra information is fine; this warning is here to catch misspelled optional column names.
> in line 1 of agency.txt
> agency_id agency_name agency_url  agency_timezone agency_lang agency_phone    agency_fare_url agency_email

I copied the field name from  the GTFS reference:
https://developers.google.com/transit/gtfs/reference#agencytxt

**Comment by jamescr** [comment]
@aledelgo this issue was fixed and this issue should be closed.
