### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by HonzaMac** [google/transitfeed#430]
Is it possible to tag new version?

cc @bdferris

**Comment by jamescr** [comment]
cc: @RachM

**Comment by RachM** [comment]
Sure, contributions are very welcome! I'll review and merge commits :-)

**Comment by grote** [comment]
@RachM  This is not about a code change this time, but about tagging and releasing a new version that contains all code changes and then uploading it to pypi. The [last version there](https://pypi.python.org/pypi/transitfeed) is from beginning of 2015.

**Comment by RachM** [comment]
Done.

**Comment by qwasar** [comment]
@RachM Would you please create a 1.2.16 release (https://github.com/google/transitfeed/releases) and tag it in the repository as well?

**Comment by grote** [comment]
Thanks @RachM for the quick release!

I agree with @qwasar that it would be nice to at least also push the tag of the release to github.

**Comment by RachM** [comment]
No problem - done (although it's missing a windows exe - let me know if that's an issue).

**Comment by besangez** [comment]
Hi @RachM 

Can you possibly also provide a windows exe for the latest available release (1.2.16)? 

Thank you,
