### ISSUE TITLE
Schedule Viewer shows error for location_type = 2

### ISSUE THREAD

**Issue by twopelu** [google/transitfeed#437]
When I try loading a GTFS feed in the Schedule Viewer shows these errors:

![image](https://user-images.githubusercontent.com/12948190/33946325-c7f8c070-e021-11e7-969d-22e1a33fd44f.png)

If I try validating it with the Feed Validator and the same errors are reported:

[validation-results.zip](https://github.com/google/transitfeed/files/1556023/validation-results.zip)

This seems to make a lot of stops not to appear in the map.

When I load it in other route planners (I use mainly the Open Trip Planner) it loads the entire transport network correctly with no errors.

**Comment by Bertware** [comment]
This should have been fixed in PR #488

**Comment by jarondl** [comment]
indeed. Thank you @Bertware
