### ISSUE TITLE
Time Travel Error

### ISSUE THREAD

**Issue by shaaaarpy** [google/transitfeed#474]
When the arrival time goes from 23hr to 00hr it shows time travel error. Actually it goes to a new day. 
Can you please confirm.
Thank you

**Comment by BraveJhawk** [comment]
The arrival time should go from 23hr to 24hr to indicate that it is midnight the next day rather than midnight the same day.

e.g.
stop_order,arrival_time
1,23:59:00
2,24:05:00

**Comment by BraveJhawk** [comment]
Review the information on https://developers.google.com/transit/gtfs/reference/#stop_timestxt for more details.

**Comment by shaaaarpy** [comment]
yes its working
Thank you
