### ISSUE TITLE
Read gtfs and get the structure

### ISSUE THREAD

**Issue by picho** [google/transitfeed#478]
Hi people.

Thanks for your work.

The library says that it can read gtfs, I am trying to do that, I don´t know if is possible that i can read the gtfs and get the structure, for example the trips, stops, routes

**Comment by barbeau** [comment]
@picho If you're looking for general-purpose tools to manage and query GTFS, I'd suggest checking out this list:
https://github.com/CUTR-at-USF/awesome-transit#gtfs
