### ISSUE TITLE
Where is .exe file?

### ISSUE THREAD

**Issue by margat78** [google/transitfeed#502]
_Drag a GTFS zip file or directory onto feedvalidator.exe. A window will pop up with the result of the validation test:_

I can't find Windows standalone version.

**Comment by barbeau** [comment]
@margat78 Looks like the last release with a Windows binary was 1.2.15:
https://github.com/google/transitfeed/releases/tag/1.2.15

**Comment by KristjanESPERANTO** [comment]
Duplicate of #446

**Comment by barbeau** [comment]
Thanks @KristjanESPERANTO. Closing as duplicate of #446.
