### ISSUE TITLE
Please define GTFS

### ISSUE THREAD

**Issue by Codeberg-AsGithubAlternative-buhtz** [google/transitfeed#518]
Hi,

can you please explain what GTFS emans and put that in the README.md also?

Did you mean?
https://de.wikipedia.org/wiki/General_Transit_Feed_Specification

**Comment by abhasdudeja** [comment]
Yes, GTFS is General Transit Feed Specification.
This issue is not important in my opinion, as any person who will land on this project/git would already have researched his/her bit to find this exact project.
Thanks

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
I was not aware this is a Google project.
My apologize for investing resources into Google. :-1:
